name: Forgejo Actions
description: GitHub actions collection for Forgejo
author: You-Sheng Yang

branding:
  icon: code
  color: orange

# Define your inputs here.
inputs:
  milliseconds:
    description: Your input description here
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
